# ---------------prompts used for quantitative evaluation---------------

- neutral: "A realistic image of a person."
  positive: "A realistic image of a person, smiling widely, very happy."
  negative: "A realistic image of a person, frowning, very sad."
  guidance_scale: 9
  batch_size: 1
  tag: "smiling"

- neutral: "A realistic image of a person."
  positive: "A realistic image of a person, very old, aged, wrinkly."
  negative: "A realistic image of a person, detailed facial features, clear skin."
  guidance_scale: 9
  batch_size: 1
  tag: "age"

- neutral: "A realistic image of a car."
  positive: "A realistic image of a car, damaged, broken headlights, dented car, with scrapped paintwork."
  negative: "A realistic image of a car, mint condition, brand new, shiny."
  guidance_scale: 9
  batch_size: 1
  tag: "damaged_car"

- neutral: "A realistic image of a person."
  positive: "A realistic image of a person, wearing glasses."
  negative: "A realistic image of a person, clear face."
  guidance_scale: 9
  batch_size: 1
  tag: "glasses"

- neutral: "A realistic image of a person."
  positive: "A realistic image of a person, with makeup, cosmetic, concealer, mascara, lipstick."
  negative: "A realistic image of a person, ugly."
  guidance_scale: 9
  batch_size: 1
  tag: "lipstick"

- neutral: "A realistic image of a person."
  positive: "A realistic image of a person, very fat, chubby, overweight, obese."
  negative: "A realistic image of a person, very skinny, thin, slim, lean."
  guidance_scale: 9
  batch_size: 1
  tag: "chubby"

- neutral: "A realistic image of a room."
  positive: "A realistic image of a room, cluttered, disorganized, dirty, jumbled, scattered."
  negative: "A realistic image of a room, super organized, clean, ordered, neat, tidy."
  guidance_scale: 9
  batch_size: 1
  tag: "cluttered_room"

- neutral: "A realistic image of a person."
  positive: "A realistic image of a person, with big bushy beard."
  negative: "A realistic image of a person, clean shaven."
  guidance_scale: 9
  batch_size: 1
  tag: "beard"

- neutral: "A realistic image of a person."
  positive: "A realistic image of a person, with shocked look, surprised, stunned, amazed."
  negative: "A realistic image of a person, dull, uninterested, bored, incurious."
  guidance_scale: 9
  batch_size: 1
  tag: "surprised"

- neutral: "A realistic image of a table of food."
  positive: "A realistic image of a table of food, cooked and prepped, in dishes."
  negative: "A realistic image of a table of food, raw, natural, not prepped in any way."
  guidance_scale: 9
  batch_size: 1
  tag: "cooked_food"


# --------------additional prompts used for qualitative results---------------

- neutral: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic."
  positive: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, very fat, chubby, overweight, obese."
  negative: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, very skinny, thin, slim, lean."
  guidance_scale: 9
  batch_size: 1
  tag: "chubby_realistic"

- neutral: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic."
  positive: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, smiling widely, very happy."
  negative: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, realistic background that outside with depth of field, photorealistic, frowning, very sad."
  guidance_scale: 9
  batch_size: 1
  tag: "smiling_realistic"

- neutral: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic."
  positive: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, very old, aged, wrinkly."
  negative: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, very young, clear skin."
  guidance_scale: 9
  batch_size: 1
  tag: "age_realistic"

- neutral: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic."
  positive: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, wearing glasses."
  negative: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, clear face."
  guidance_scale: 9
  batch_size: 1
  tag: "glasses_realistic"

- neutral: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic."
  positive: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, with makeup, cosmetic, concealer, mascara, lipstick."
  negative: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, bare face."
  guidance_scale: 9
  batch_size: 1
  tag: "lipstick_realistic"

- neutral: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic."
  positive: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, with big bushy beard."
  negative: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, clean shaven."
  guidance_scale: 9
  batch_size: 1
  tag: "beard_realistic"

- neutral: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic."
  positive: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, with shocked look, surprised, stunned, amazed."
  negative: "A natural portrait photo of a person, upper body shot, captured with a DSLR camera, realistic facial features, natural skin texture, soft lighting, detailed clothing, background of a park with depth of field, photorealistic, dull, uninterested, bored, incurious."
  guidance_scale: 9
  batch_size: 1
  tag: "surprised_realistic"


- neutral: "A realistic image of a dog playing in a park, realistic background, furry, sunny."
  positive: "A realistic image of a very light all white dog playing in a park, realistic background, all light white fur."
  negative: "A realistic image of a very dark all black dog playing in a park, realistic background, all dark black fur."
  guidance_scale: 9
  batch_size: 1
  tag: "dog_fur"

- neutral: "A highly realistic portrait of a person, photographed at head-and-shoulders distance. Natural sunlight streams through a nearby window, softly illuminating the face with warm tones. subtle décor, creating a cinematic and natural background. Captured with a DSLR camera, sharp focus on the person’s face, natural skin texture, realistic lighting."
  positive: "A photorealistic portrait of a person, smiling widely, very happy, very old, aged, wrinkly."
  negative: "A photorealistic portrait of a person, frowning, very sad, detailed facial features, clear skin."
  guidance_scale: 9
  batch_size: 1
  tag: "smiling_age_composition"
